services:
    # frontend:
    #     container_name: snapcast-ui
    #     image: snapcast-ui
    #     env_file:
    #         - "./.env"
    #     build:
    #         context: .
    #         dockerfile: .docker/DockerfileLocal
    #     ports:
    #         - "3000:3000"
    #     volumes:
    #       - "/app/node_modules"
    #       - "./:/app/"
    snapcastServer:
        container_name: snapcast-server
        image: snapcast-server
        build:
            context: .
            dockerfile: .docker/DockerfileSnapcastServer
        ports:
            - "1780:1780"