version: '3'
services:
    frontend:
        env_file:
            - "./.env"
        environment:
            REACT_APP_SNAPCAST_HOST: "ws://localhost:1780"
        build:
            target: dev
        ports:
            - "3000:3000"
        volumes:
          - "/app/node_modules"
          - "./:/app/"

    snapcast-server:
        build:
            dockerfile: docker/DockerfileSnapcast
            target: server
        ports:
            - "1780:1780"
            - "1704:1704"

    snapcast-client:
        command:
            - "--logfilter=warning"
            - "--instance=1"
        build:
            dockerfile: docker/DockerfileSnapcast
            target: client

    snapcast-client2:
        command:
            - "--logfilter=warning"
            - "--instance=2"
        build:
            dockerfile: docker/DockerfileSnapcast
            target: client

    snapcast-client3:
        command:
            - "--logfilter=warning"
            - "--instance=3"
        build:
            dockerfile: docker/DockerfileSnapcast
            target: client

    snapcast-client4:
        command:
            - "--logfilter=warning"
            - "--instance=4"
        build:
            dockerfile: docker/DockerfileSnapcast
            target: client

    snapcast-client5:
        command:
            - "--logfilter=warning"
            - "--instance=3"
        build:
            dockerfile: docker/DockerfileSnapcast
            target: client
